Add ServiceMonitor in helm chart
longhorn/charts pull request #97
Opened 2023-02-01 10:58 UTC by enrico9034

To ensure you can create the service monitor without having to deploy it manually after installation, I added a values **metrics.serviceMonitor.enabled**. The default values is **false**, but if set to **true** it creates the service monitor according to the documentation.

2023-02-15 06:01 UTC, innobead reviewed
This depends on https://longhorn.io/docs/1.4.0/monitoring/prometheus-and-grafana-setup/#install-prometheus-operator, but we don't actually enforce users to use this stack. Don't feel to make this part of the volume good for now until we have an opininated builtin integration for monitoring.

2023-02-15 06:06 UTC, innobead approved these changes
`metrics.serviceMonitor.enable` seems specific for service monitor, so it should is acceptable.

2023-02-15 06:07 UTC, innobead commented
cc @longhorn/qa Can you help with the testing?

2023-03-14 03:57 UTC, yangchiu commented
Verified if `metrics.serviceMonitor.enabled` set to `true`, the corresponding service monitor can be created:
```
$ kubectl get ServiceMonitor -n longhorn-system
NAME                                 AGE
longhorn-prometheus-servicemonitor   2m16s

$ kubectl get ServiceMonitor longhorn-prometheus-servicemonitor -n longhorn-system -o yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: longhorn
    meta.helm.sh/release-namespace: longhorn-system
  creationTimestamp: "2023-03-14T03:50:37Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.4.0
    helm.sh/chart: longhorn-1.4.0
    name: longhorn-prometheus-servicemonitor
  name: longhorn-prometheus-servicemonitor
  namespace: longhorn-system
  resourceVersion: "18755"
  uid: 9b5b67fa-264f-4a9c-aecf-b82612cf253b
spec:
  endpoints:
  - port: manager
  namespaceSelector:
    matchNames:
    - longhorn-system
  selector:
    matchLabels:
      app: longhorn-manager
```

2023-04-11 08:25 UTC, enrico9034 commented
Hi, any update on this? Can you merge it?

2023-06-03 10:03 UTC, Flou21 commented
Hey,

I was about to deploy Longhorn in a new cluster and set up monitoring for it.
So exactly what is improved here, would be cool if this could be merged

2023-06-03 11:42 UTC, innobead commented
See if we can make this part of the following release.

2023-06-06 01:08 UTC, PhanLe1010 approved these changes
LGTM

2023-06-06 01:10 UTC, PhanLe1010 commented
@yangchiu  could you please verify that Prometheus is able to fetch the metrics using the serviceMonitor?  

> Verified if `metrics.serviceMonitor.enabled` set to `true`, the corresponding service monitor can be created:
> 
> ```
> $ kubectl get ServiceMonitor -n longhorn-system
> NAME                                 AGE
> longhorn-prometheus-servicemonitor   2m16s
> 
> $ kubectl get ServiceMonitor longhorn-prometheus-servicemonitor -n longhorn-system -o yaml
> apiVersion: monitoring.coreos.com/v1
> kind: ServiceMonitor
> metadata:
>   annotations:
>     meta.helm.sh/release-name: longhorn
>     meta.helm.sh/release-namespace: longhorn-system
>   creationTimestamp: "2023-03-14T03:50:37Z"
>   generation: 1
>   labels:
>     app.kubernetes.io/instance: longhorn
>     app.kubernetes.io/managed-by: Helm
>     app.kubernetes.io/name: longhorn
>     app.kubernetes.io/version: v1.4.0
>     helm.sh/chart: longhorn-1.4.0
>     name: longhorn-prometheus-servicemonitor
>   name: longhorn-prometheus-servicemonitor
>   namespace: longhorn-system
>   resourceVersion: "18755"
>   uid: 9b5b67fa-264f-4a9c-aecf-b82612cf253b
> spec:
>   endpoints:
>   - port: manager
>   namespaceSelector:
>     matchNames:
>     - longhorn-system
>   selector:
>     matchLabels:
>       app: longhorn-manager
> ```

2023-06-06 01:14 UTC, PhanLe1010 requested changes
Oh wait. This is not the correct repo. Please create PR into https://github.com/longhorn/longhorn/tree/master/chart instead @enrico9034

2023-06-19 12:43 UTC, enrico9034 commented
> To ensure you can create the service monitor without having to deploy it manually after installation, I added a values **metrics.serviceMonitor.enabled**. The default values is **false**, but if set to **true** it creates the service monitor according to the documentation.

Done this is the PR https://github.com/longhorn/longhorn/pull/6157

2024-02-11 22:24 UTC, 98jan commented
would this change still work when NetworkPolicies are enabled?
I tried today to scrape the metrics with the enabled ServiceMonitor:   https://github.com/longhorn/longhorn/blob/3e04f753f2449ef9d91b623b4b4263c6c843bd9b/chart/values.yaml#L464

But the connection is failing, as the available NetworkPolicies would block this request.

2024-06-05 08:43 UTC, avk999 commented
Many installations require specific labels/annotations/namespace for serviceMonitor and other prometheus stack objects. Would be great to have those configurable like:
```yaml
metrics:
   serviceMonitor:
     enabled: true
     additional_labels: {}
```

2025-10-16 04:12 UTC, derekbit commented
Please don't create a PR in this repo.
You can create an improvement ticket in [longhorn/longhorn/issues](https://github.com/longhorn/longhorn/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) and a PR in [longhorn/longhorn](https://github.com/longhorn/longhorn). We will review and discuss with you there. Thank you.

2025-10-16 04:12 UTC, closed without merging